In [58]:
import numpy as np
import sys

## Basic


In [7]:
a1 = np.array([2,3,4], dtype = "int32")
print(a1)

[2 3 4]


In [8]:
a2 = np.array([[10.0,11.0,12.0], [7.0,8.0,9.0]])
print(a2)

[[10. 11. 12.]
 [ 7.  8.  9.]]


In [13]:
#Get dimension --> .ndim
print("dimension of a1 = " + str(a1.ndim))
print("dimension of a2 = " + str(a2.ndim))


dimension of a1 = 1
dimension of a2 = 2


In [15]:
#Get shape --> rows and columns --> .shape
print("shape of a1 : " + str(a1.shape))
print("shape of a2 : " + str(a2.shape))

shape of a1 : (3,)
shape of a2 : (2, 3)


In [16]:
#Get type
a1.dtype

dtype('int32')

In [21]:
#Get size (in bytes)
print(a1.itemsize)
print(a1.size) #no.of elements

4
3


In [19]:
#Get total size , a.size --> no.of elements 
(a1.size)*(a1.itemsize) #3*4

12

## Accessing/Changing specific elements, rows, columns, etc


In [9]:
a1 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
print(a1.shape)
print(a1.itemsize)

(2, 7)
4


In [14]:
#Get a specific element (r,c)
a1[1,5] #or
a1[1,-2]

13

In [15]:
#Get a specific row
a1[0,:] #or 
a1[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
#Get a specific column
a1[:,2]

array([ 3, 10])

In [30]:
# [startindex:endindex:stepsize]
a1[0, 1:6:2] #or
a1[0, 1:-1:2]

array([2, 4, 6])

In [33]:
#Changing the value of the 5th element in the 2nd list (12) to 15
a1[1,4] = 15
#print(a)

a1[:, 1] = 4 #Replacing the 2rd element of both the rows with 4
#print(a)

a1[:, 3] = [2,3] #Replacing the 4th element of 1st list with 2 and 2nd list with 3
print(a1)

a1.shape

[[ 1  4  3  2  5  6  7]
 [ 8  4 10  3 15 13 14]]


(2, 7)

In [36]:
#3-D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [37]:
#Getting specific element (Work outside in)
b[1, 0, 1] #To get 6

6

In [38]:
#Replace 
b[:, 1, :] = [[9,10],[11,12]]
b

array([[[ 1,  2],
        [ 9, 10]],

       [[ 5,  6],
        [11, 12]]])

## Initializing Different Types of Arrays

In [3]:
#All 0s matrix
zr = np.zeros((2,3,3,2))
print(zr)
print(zr.ndim)
print(zr.size)
print(zr.itemsize)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]
4
36
8


In [4]:
one = np.ones((2,2,2))
print(one)
#one.ndim
#one.shape
#one.size
one.itemsize

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


8

In [84]:
o1 = np.ones((4,2,2))
print(o1)
#o1.size
o1.itemsize

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


8

In [5]:
#Any other number
n = np.full((2,2),22, dtype='float32' )
print(n)
n.size

[[22. 22.]
 [22. 22.]]


4

In [10]:
#Any other number (full_like)
fl = np.full_like(a1,2)
print(fl)
fl.ndim
fl.shape
fl.size

[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]


14

In [11]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.70863512, 0.58205179],
       [0.90173852, 0.65218906],
       [0.1065867 , 0.78684576],
       [0.76323173, 0.04366005]])

In [12]:
#random integer values
r = np.random.randint(2,10,size=(3,3)) #(start,stop,matrix shape)
print(r)
r.size

[[8 3 2]
 [8 4 9]
 [2 5 6]]


9

In [13]:
#To get identity matrix
i = np.identity(3, dtype="int32")
print(i)
#i = np.array([[1,0,0],[0,1,0],[0,0,1]])
#print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [15]:
#To repeat an array
ar = np.array([[4,5,6]])
rp1=np.repeat(ar,3, axis=1) #[[4 4 4 5 5 5 6 6 6]]
rp2 = np.repeat(ar,3, axis=0)
print(rp1)
print(rp2)

[[4 4 4 5 5 5 6 6 6]]
[[4 5 6]
 [4 5 6]
 [4 5 6]]


In [17]:
o2 = np.ones((5,5))
print(o2)


z = np.zeros((3,3))
z[1,1] = 5
print(z)

o2[1:4, 1:4] = z
print(o2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 5. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 5. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [18]:
a = np.array([4,5,6])
b = a.copy() #if you take b = a and manipulate b, the changes will also be applied to a
b[0] = 200
print(a)
print(b)

[4 5 6]
[200   5   6]


## Mathematics

In [19]:
a = np.array([100,200,300,400])
print(a)

[100 200 300 400]


In [20]:
a + 20

array([120, 220, 320, 420])

In [21]:
a - 20

array([ 80, 180, 280, 380])

In [22]:
a * 6

array([ 600, 1200, 1800, 2400])

In [23]:
a / 2

array([ 50., 100., 150., 200.])

In [24]:
b = np.array([100,0,100,0])
a + b 

array([200, 200, 400, 400])

In [25]:
a ** 2

array([ 10000,  40000,  90000, 160000], dtype=int32)

In [27]:
#take the sine, cosine
print(np.sin(a))
print(np.cos(a))

[-0.50636564 -0.8732973  -0.99975584 -0.85091936]
[ 0.86231887  0.48718768 -0.02209662 -0.52529634]


## Linear Algebra

In [29]:
#To multiply two matrices
a = np.full((2,3), 2)
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)


[[2 2 2]
 [2 2 2]]
[[2 2]
 [2 2]
 [2 2]]


array([[12, 12],
       [12, 12]])

In [30]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
#Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
#Determinant
#Trace
#Singular Vector Decomposition
#Eigenvalues
#Matrix norm
#Inverse
#Etc...

## Statistics

In [32]:
stat = np.array([[4,5,6],[7,8,9]])
stat

array([[4, 5, 6],
       [7, 8, 9]])

In [36]:
np.max(stat)

9

In [37]:
np.min(stat)

4

In [38]:
np.mean(stat)

6.5

In [39]:
np.median(stat)

6.5

In [40]:
np.sum(stat)

39

## Reorganising Arrays

In [42]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

after = before.reshape(6,1)
print(after)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [44]:
# Vertically stacking vectors
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
np.vstack([vec1,vec2,vec1,vec2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [46]:
# Horizontal stack
hor1 = np.ones((2,4))
hor2 = np.zeros((2,7))

np.hstack((hor1,hor2))

array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.]])

## Miscellaneous

### Load Data from File

In [59]:
data = np.genfromtxt("C:\Aditi\My Work\Summer\Python YT\numpyfile.txt", delimiter = ',')
#print(file)
#file = file.astype('int32') #Converts data to integer type, makes a copy without assignment
#file

OSError: C:\Aditi\My Work\Summer\Python YT
umpyfile.txt not found.

### Boolean Masking & Advanced Indexing

In [11]:
data > 50  #Gives boolean values 

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [12]:
data[data>50]  #Gives an array of the integers satisfying the condition

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [14]:
#You can index a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] 

array([2, 3, 9])

In [15]:
np.any(data>50, axis=0) #Gives boolean values for the columns (if any value in each column has an integer >50, gives True)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(data>50, axis=0) #Gives boolean values for the columns (if all the values in each column has an integer >50, gives True)

In [17]:
(~((data>50) & (data<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])